ReseumeUpload/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ResumeApp.urls')),
]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ResumeApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home.as_view(),name='home'),
    path('all_candidates/', views.all_candidates.as_view(),name='all_candidates'),

]

ResumeApp/models.py
from django.db import models

# Create your models here.

class ResumeModel(models.Model):
    fname = models.CharField(max_length=100)
    lname = models.CharField(max_length=100)
    email = models.EmailField()
    contact = models.CharField(max_length=100)
    gender = models.CharField(max_length=100)
    dob = models.DateField()
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    language = models.CharField(max_length=100)
    programming_language = models.CharField(max_length=100)
    education = models.CharField(max_length=100)
    prefered_loc = models.CharField(max_length=100)
    prof_image = models.ImageField(upload_to='Profile_Image/',blank=True)
    project = models.TextField()

ResumeApp/forms.py
from django import forms
from.models import ResumeModel

# value - label
gender_choices = [("male","male"),("female", 'female'), ('other', 'other')]

city_choics = [("Thane", 'Thane'), ("vashi", 'vashi'), ("kurla",'kurla')]

state_choices = [("Maharashtra","Maharashtra"), ("Mp", "Mp"), ("up", "up")]

language_choices = [("Hindi", 'Hindi'), ("Marathi", "Marathi"), ("english", "english"), ('gujrati', 'gujrati'), ("tamil", "tamil")]

prog_lang_choices = [('C#', 'C#'), ("C", "C"), ("C++", "C++"),("Java", "java"), ("Python", "Python"), ('Asp.net', 'Asp.net')]

#education_choices = [("BSC", "BSC"), ('BSC-IT',"BSC-IT"), ("BE", "BE"), ("BCom", 'BCome'), ("BSC-CS", "BSC-CS")]

preferred_loc_choices = [('Vashi', "vashi"),("Thane", 'Thane'), ("Kurla", "kurla"), ("kalyan", "kalyan")]



class ResumeForm(forms.ModelForm):

    gender = forms.ChoiceField(choices=gender_choices, label = "Gender", widget = forms.RadioSelect)
    city = forms.ChoiceField(choices=city_choics, label='Select city', widget=forms.Select(attrs={'class':'form-control'}))
    state = forms.ChoiceField(choices=state_choices, label = "State", widget= forms.Select(attrs={'class':'form-control'}))

    language = forms.MultipleChoiceField(choices=language_choices, label = "Select Language", widget= forms.CheckboxSelectMultiple)

    programming_language= forms.MultipleChoiceField(choices=prog_lang_choices, label = 'Select Programming Language', widget=forms.CheckboxSelectMultiple)

    #education = forms.ChoiceField(choices=education_choices, label = "Select Education", widget=forms.RadioSelect)

    prefered_loc = forms.ChoiceField(choices=preferred_loc_choices, label = 'Select Preferred Location', widget=forms.Select(attrs={'class':'form-control'}))



    class Meta:
        model = ResumeModel
        fields = ['id','fname','lname','email','contact','gender','dob','city','state','language','programming_language','education','prefered_loc','prof_image','project']

        labels= {
            'fname' : 'First Name',
            'lname' : 'Last Name',
            'email' : 'Email ID',
            'contact' : 'Contact number',
            #'gender' : 'Gender',
            'dob' : 'Date of Birth',
            'city' : 'City',
            'state': 'State',
            'language' : 'Languages',
            'programming_language' : 'Technical Skills',
            'education' : 'Education',
            'prefered_loc' : 'Prefered Location',
            'prof_image' : ' Upload Profile Photo',
            'project' : 'Project'
        }

        widgets = {
            'fname' : forms.TextInput(attrs={"class": "form-control"}),
            'lname' : forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'contact': forms.TextInput(attrs={'class': "form-control"}),
            'dob' : forms.DateInput(attrs={'class':'form-control'}),
            'education': forms.TextInput(attrs={'class': 'form-control'}),
            'prof_image' : forms.FileInput(attrs={'class':'form-control'}),
            'project': forms.Textarea(attrs={'class':'form-control'})

            

        }





# for dateinput add jquery datepicker in base.html

ResumeApp/views.py
from django.shortcuts import render, redirect
from.forms import ResumeForm
from django.views import View
from.models import ResumeModel

# Create your views here.

# def home(request):
#     forms = ResumeForm()
#     context = {'forms':forms}
#     return render(request,'ResumeApp/home.html', context)

class home(View):
    def get(self,request):
        forms = ResumeForm()
        context = {'forms':forms}
        return render (request,"ResumeApp/home.html",context)

    def post(self,request):
        forms = ResumeForm(request.POST,request.FILES)
        if forms.is_valid():
            forms.save()
            return redirect('all_candidates')
            
        return redirect('home')

class all_candidates(View):
    def get(self, request):
        data=ResumeModel.objects.all()
        context={'data':data}
        return render(request,'ResumeApp/allcandidate.html',context)

templates/ResumeApp/allcandidate.html
{% extends 'ResumeApp/base.html' %}

{% block css %}
{% endblock css %}

{% block js %}
{% endblock js %}

{% block title %}
<title>All Candidate Page</title>
{% endblock title %}

{% block body %}

<div class="container py-4">

    {% for d in data %}
    <div class="container p-3 my-3 shadow rounded">
        <img src="{{d.prof_image.url}}" alt="" height="150px">
        <a href="">{{d.email}}</a>
    </div>
    {% endfor %}
</div>

{% endblock body %}

templates/ResumeApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">

    <!-- jquery datepicker --> 
    <!-- https://jqueryui.com/datepicker/ -->
    <!-- 1. links   2. home  function in js block -->

    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

    {% block css %}
    {% endblock css %}

    {% block js %}
    {% endblock js %}

    {% block title %}
    {% endblock title %}


</head>
<body>

    {% include "ResumeApp/nav.html" %}

    {% block body %}
    {% endblock body %}
    
</body>
</html>

templates/ResumeApp/home.html
{% extends 'ResumeApp/base.html' %}


{% block css %}
{% endblock css %}

{% block js %}
<script>
    $(document).ready(function(){
        $( "#id_dob" ).datepicker({changeMonth:true, changeYear:true,yearRange: '1950:2049'});

    
    })
</script>

{% endblock js %}

{% block title %}
<title>Home Page</title>
{% endblock title %}



{% block body %}
<div class="container mt-3">
    <!-- Header -->
<div class="container bg-secondary shadow rounded-3">
    <h1 class="text-center text-light">Upload Resume</h1>
</div>

<div class="container shadow w-50">
    <form action="{% url 'home' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for i in forms %}
        <div class="mb-3">
            {{i.label_tag}}
            {{i}}
            <span style="color: red;">{{i.errors}}</span>

    
        </div>
        {% endfor %}

        <div class="mb-3 text-center">

            <input type="submit" value="Submit" class="btn btn-primary">
        </div>

    </form>
</div>

</div>
{% endblock body %}

templates/ResumeApp/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid text-center">
      <a class="navbar-brand" href="{% url 'home' %}"><i class="bi bi-house-fill"></i></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'all_candidates' %}">All Candidates</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About Us</a>
          </li>
          <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a> -->
            <!-- <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul> -->
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li> -->
        </ul>
        <form class="d-flex">
          <!-- <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"> -->
          <!-- <button class="btn btn-outline-success" type="submit">Search</button> -->
        </form>
      </div>
    </div>
  </nav>